Traceback (most recent call last):
  File "C:\Users\morishita\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\morishita\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\morishita\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\morishita\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\morishita\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\morishita\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\morishita\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\morishita\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd    # pandasを取り込み、pdという名前で使う、という命令

df = pd.DataFrame()           # 空のDataFrame
df["A"] = [11,32,3,7,53,12]   # A列にデータを追加
print(df[df["A"] > 20])       # A列で20より大きい値を抽出して表示
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn [1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m    [38;5;66;03m# pandasを取り込み、pdという名前で使う、という命令[39;00m
[0;32m      3[0m df [38;5;241m=[39m pd[38;5;241m.[39mDataFrame()           [38;5;66;03m# 空のDataFrame[39;00m
[0;32m      4[0m df[[38;5;124m"[39m[38;5;124mA[39m[38;5;124m"[39m] [38;5;241m=[39m [[38;5;241m11[39m,[38;5;241m32[39m,[38;5;241m3[39m,[38;5;241m7[39m,[38;5;241m53[39m,[38;5;241m12[39m]   [38;5;66;03m# A列にデータを追加[39;00m

[1;31mModuleNotFoundError[0m: No module named 'pandas'
ModuleNotFoundError: No module named 'pandas'

